# Generated by Django 5.0.7 on 2024-07-23 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tableDetail', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='technology',
            new_name='IssueID',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='convID',
        ),
    ]
